### ISSUE TITLE
Panagram Service error: Service always returning status code of 200 with response “pangram = true” even if the string passed in a NON-pangram string

### ISSUE THREAD

**Issue by deepure1220** [deepure1220/Pangram-api-test#1]
**Summary**: Seems that the service is always returning true no matter what ever string is passed.

**Steps to reproduce:**
1.	Open the API using the URL Below
https://app.swaggerhub.com/apis-docs/mlaguren/pangram/1.0.1/#/default/post_pangram
2.	Use the SWAGGER hub to do the posting.
3.	Edit the string in request JSON call as pass a non-pangram string and execute the call.
Non Pangram String: "A quick brown fox jumped over the lazy brown dog"
Expected: The response expected is “pangram”: false
Actual: The response us is “pangram”: true

See snapshot for details.

Also attached is the list of TC’s for testing the WebService
![pangarm ws test error](https://user-images.githubusercontent.com/45053529/48568149-87353000-e8b3-11e8-9606-cdfee408b3db.gif)
[Test Case for API.xlsx](https://github.com/deepure1220/Pangram-api-test/files/2586259/Test.Case.for.API.xlsx)

**Comment by melvin-mbww** [comment]
A quick scan of the string shows that every letter of the alphabet is there.  Changing "The" to "A" has no effect, because "the" is still being submitted to the API from "the lazy brown dog".  If you remove either "fox" or "lazy", you will receive false as there is no other occurrence of the letter 'x' or 'z'.

**Comment by deepure1220** [comment]
You are correct. 
I also tested the API will Blank string, Less than 26 alphabets but still its return true. See the snapshot.

![pangarm ws test error1](https://user-images.githubusercontent.com/45053529/48573245-7939dc00-e8c0-11e8-9680-0fcdfd512be3.gif)
et chars, but received

**Comment by melvin-mbww** [comment]
Swaggerhub will always return what I have in the documentation.  The actual url you need to test against is:

https://pangram-api.herokuapp.com/pangram which is the working implementation of the swagger documentation.

**Comment by melvin-mbww** [comment]
You mentioned tests, but nothing was in the email I received and couldn't find anything in Github.  Let me know if you have any questions.
